%% Display setting and output setup
% set(0,'ShowHiddenHandles','on'); delete(get(0,'Children')); % close windows
scr = get(groot,'ScreenSize');                              % screen resolution
phi = (1 + sqrt(5))/2;
scr_ratio = phi/3;
offset = [ scr(3)/4 scr(4)/4]; 
fig_pos = [offset(1) offset(2) scr(3)*scr_ratio scr(4)*scr_ratio];
figOutputClosed =  figure('Position',fig_pos);
set(figOutputClosed,'numbertitle','off',...                            % Give figure useful title
        'name','Input and Output data from BlackBox',...
        'Color','white');
fontName='CMU Serif';
fontSize = 28;
set(0,'defaultAxesFontName', fontName);                     % Make fonts pretty
set(0,'defaultTextFontName', fontName);
set(0,'DefaultAxesColor','none');                           % Transparent background
set(groot,'FixedWidthFontName', 'ElroNet Monospace')     

% data



y = [cell2mat(in_data);...
    cell2mat(target_data)];
x = t;

% Colors
cmap = colormap(lines);

line_thin = 2;
line_thick = 3;
marker_size = 8;
marker_spacing = 1000;
len = length(x);
    
% Draw plots
subplot(2,1,1);
    axInput = gca;   
    p_Input = plot(x,y(1,:),...
        'Color', cmap(1,:),...
        'DisplayName','Input',...
        'LineStyle','-',...
        'LineWidth',line_thin);
    title('Input')
    hold on

    % Axes and labels
    set(axInput,'FontSize',fontSize,...
        'Color','none',...
        'Box','off',...
        'XAxisLocation','bottom',...
        'YMinorTick','on',...
        'XMinorTick','on',...
        'TickDir','both',...
        'Layer','top',...
        'LineWidth',line_thin,...
        'TickLabelInterpreter','latex');
    set(axInput,...
        'Xlim',[ceil(min(min(x))) ceil(max(max(x)))],...
        'Ylim',[floor(min(min(y(1,:)))) ceil(max(max(y(1,:))))]);
    hold on
%     xlabel('Time [s] \rightarrow',...
%         'FontName',fontName,...
%         'FontSize',fontSize);
%     ylabel('Voltage [V] \rightarrow',...
%         'FontName',fontName,...
%         'FontSize',fontSize);


subplot(2,1,2);
    axOutput = gca;   
    p_Output = plot(x,y(2,:),...
        'Color', cmap(2,:),...
        'DisplayName','Output',...
        'LineStyle','-',...
        'LineWidth',line_thin);
    title('Output')
    hold on

    % Axes and labels
    set(axOutput,'FontSize',fontSize,...
        'Color','none',...
        'Box','off',...
        'XAxisLocation','bottom',...
        'YMinorTick','on',...
        'XMinorTick','on',...
        'TickDir','both',...
        'Layer','top',...
        'LineWidth',line_thin,...
        'TickLabelInterpreter','latex');
    set(axOutput,...
        'Xlim',[ceil(min(min(x))) ceil(max(max(x)))],...
        'Ylim',[floor(min(min(y(2,:)))) ceil(max(max(y(2,:))))]);
    hold on
%     xlabel('Time [s] \rightarrow',...
%         'FontName',fontName,...
%         'FontSize',fontSize);
%     ylabel('Voltage [V] \rightarrow',...
%         'FontName',fontName,...
%         'FontSize',fontSize);

% Legend
% legend1 = legend;
% set(legend1,...
%      'Position',[0.404700326122332 0.210131556174964 0.233108108108108 0.132394109235202],...
%      'Box','off');
% hold on

axMain = axes('Visible','off');
    txt_x =('Time [s] \rightarrow');
    txt_y = ('Voltage [V] \rightarrow');
    
    x_label = text(axMain,0.4,-0.09,txt_x,...
        'FontName',fontName,...
        'FontSize',fontSize);
    y_label = text(axMain,-0.14,0.4,txt_y,...
        'FontName',fontName,...
        'FontSize',fontSize,...
        'Rotation',90);

% Adjust figure
axMain = FillAxesPos(axMain,0.99);
axInput.Position = FillAxesPos(axInput,0.9);
axOutput.Position = axInput.Position;
axOutput.Position = [axOutput.Position(1) axOutput.Position(2)-0.5...
                     axOutput.Position(3) axOutput.Position(4)];
% set(gca,'Layer','bottom')





hold off

clear ax1 ax2 cmap fontName fontSize legend1 len line_thin line_thick marker_size
clear marker_spacing offset p_hi p_lo p_nominal phi r1 r2 r3 scr scr_ratio